### ISSUE TITLE
Embed stuff for Twitter, Slack, etc.

### ISSUE THREAD

**Issue by jbenet** [multiformats/website#21]
We should add the necessary html and images to make sure all the social networking things embed links to the site with a nice image and description.

should at least work on: 
- [ ] `/`
- [ ] `/multihash`

**Comment by dignifiedquire** [comment]
I can take this

**Comment by dignifiedquire** [comment]
ref for self: https://medium.com/slack-developer-blog/everything-you-ever-wanted-to-know-about-unfurling-but-were-afraid-to-ask-or-how-to-make-your-e64b4bb9254#.hn8cjgb4n

**Comment by lgierth** [comment]
What's Slack gonna be?

**Comment by dignifiedquire** [comment]
> What's Slack gonna be?

Not sure what you mean with this

**Comment by lgierth** [comment]
Aah I just got it. This is about embed stuff as in twitter cards, and the link cards in slack. Got it, nevermind :)
