### ISSUE TITLE
width of the new header and footer doesn't match the width of the content

### ISSUE THREAD

**Issue by diasdavid** [multiformats/website#28]
# New
![image](https://user-images.githubusercontent.com/1211152/28069444-6837ac82-6641-11e7-816b-6061ca98034f.png)

# Old
![image](https://user-images.githubusercontent.com/1211152/28069451-702b3436-6641-11e7-8259-481ffb94a298.png)

👍 for making the header richer
🤔 can we make sure the header size matches the content size? seems off this way.

@richsilv

**Comment by richsilv** [comment]
@diasdavid I think the width of both needs to change if they're to be the same:
* the header (which is based on ipld.io) won't fit in a 720px container, which is the width of the current multiformats.io page.
* the measure of the body text will be too wide to be readable if its width is the same as the header.

How do you feel about having them both 820px wide?

![multiformats](https://user-images.githubusercontent.com/3180526/28075747-52e49940-6654-11e7-905b-7c9570d6bb6e.png)

**Comment by diasdavid** [comment]
@richsilv looks good in the screenshot at least :)
