### ISSUE TITLE
make build leaves a lingering watcher for less

### ISSUE THREAD

**Issue by diasdavid** [multiformats/website#29]
![image](https://user-images.githubusercontent.com/1211152/28069657-2128bbfa-6642-11e7-8679-ec93fbf8bd8f.png)

@richsilv

**Comment by richsilv** [comment]
@diasdavid could you confirm that this isn't the result of previously running `make dev` without `make dev-stop` before you built the site for prod?  I can't recreate this issue with only `make build`.

**Comment by diasdavid** [comment]
@richsilv seems that is the case. Can we make the watchers go away with `ctrl^c`?

**Comment by diasdavid** [comment]
@RichardLitt has solved this . Thank you!

**Comment by RichardLitt** [comment]
I did? Huh. Cool.

**Comment by diasdavid** [comment]
I meant @richsilv. You are awesome too, @RichardLitt  :)
