### ISSUE TITLE
Get feedback

### ISSUE THREAD

**Issue by RichardLitt** [multiformats/website#4]
@dignifiedquire @jbenet Thoughts? 

I need to overhaul the copy for the README, but this is a good start.

**Comment by dignifiedquire** [comment]
Good start agreed, a couple of notes

- not sure the badges should be here
- not sure the toc should be part of this
- I like the tables :) but would love some color for the status, like red, green and yellow lights
- It would be awesome if the `@username`s could be links to the github profiles
- source should be rather at the top than the bottom
- project maintained by at the bottom needs updating.

**Comment by Kubuxu** [comment]
I fee like the font is a bit too thin as for the lower contrast (which is good) between the foreground and the background.

Some fonts are designed for reduced contrast, and some for black and white.

**Comment by RichardLitt** [comment]
Addressed a few of those comments. New: https://ipfs.io/ipfs/Qmcp3dm1rRvCD6BMtbphYPnNFETyhEYEBN5y7BnUKJUPqy/_site. 

I think the ToC should be there - this is a long document, as it is. We could make it a navbar?
The tables should be colorized. 
Will add links.

**Comment by diasdavid** [comment]
MVP is there, once we get a proper full website, we will do a significant round of feedback. Thanks for the review so far!
