### ISSUE TITLE
Deploy from CircleCI

### ISSUE THREAD

**Issue by Stebalien** [multiformats/website#45]
We should deploy from CircleCI, not jenkins. @olizilla?

**Comment by olizilla** [comment]
For sure. @Stebalien can you

- Add @ipfsbot to the CI team https://github.com/orgs/multiformats/teams/ci
- Add me as an owner to this repo so I can configure circle.

**Comment by Stebalien** [comment]
Done and you're now an admin.

**Comment by olizilla** [comment]
@Stebalien something when wrong. I don't seem to have admin and I can't see ipfsbot in the CI team here https://github.com/orgs/multiformats/teams/ci

**Comment by Stebalien** [comment]
Well, I've _invited_ IPFSbot but it hasn't accepted. How rude! I've pinged infra to see if someone can login as ipfsbot and get it to accept the invite.

**Comment by Stebalien** [comment]
All done.

**Comment by hsanjuan** [comment]
I have enabled circleCI but I'm missing a github token so the IPFS deploy thing won't appear in the issues. Anyways, this should be done.

**Comment by olizilla** [comment]
I can fix the the github token part, but I need admin permissions on this repo. Steven fixed it, but something has flipped it back. Please can I get the admin bit again.

**Comment by hsanjuan** [comment]
@olizilla I fixed that yesterday when you told me where it came from on the chat

**Comment by olizilla** [comment]
please my i have admin permissions on this repo so I can keep it working?

**Comment by hsanjuan** [comment]
@olizilla I think you have an invitation waiting since yesterday:

![image](https://user-images.githubusercontent.com/1027022/59333745-48584300-8cf9-11e9-83d3-b5e01649fbd4.png)

**Comment by olizilla** [comment]
oh wat. The wonders of githubs probabilistic approach to notifications. I had an old invite from **2017** that I missed, and it seems github was benevolently deciding to not notify me again... I'm in now. Thank you!
