### ISSUE TITLE
Can't pin this website

### ISSUE THREAD

**Issue by etam** [multiformats/website#47]
I can't pin this website. Every time I try, the command hangs forever.

I found one of problematic resoures: When entering QmXXi93dQiHjX4JNaXaJtQCby6Pb5koCr6HqNHUsoSoC69 (current value of /ipns/multiformats.io) into ipfs explorer in webui, it shows something called "_previous-versions". It's not possible to access this even through https://multiformats.io/_previous-versions.

**Comment by hsanjuan** [comment]
Same here

**Comment by hsanjuan** [comment]
I published a new version and it should be well provided now.
