### ISSUE TITLE
Star link should go to https://github.com/multiformats/multiformats

### ISSUE THREAD

**Issue by jbenet** [multiformats/website#5]
Star link should go to https://github.com/multiformats/multiformats

**Comment by RichardLitt** [comment]
Fixed! ipfs.io/ipfs/Qmcp3dm1rRvCD6BMtbphYPnNFETyhEYEBN5y7BnUKJUPqy/_site

**Comment by lgierth** [comment]
@RichardLitt check out ipfs/ipfs-pages#3 for deploying
