### ISSUE TITLE
Current iteration is not resolving

### ISSUE THREAD

**Issue by gsf** [multiformats/website#6]
The link in the README for the current iteration (below) is not resolving for me. Is the hash correct?

https://ipfs.io/ipfs/QmdEGjyBK3WSn2GNXwFQFCsech6eMvkTiaMWKBpJ23iCkx/_site/

**Comment by lgierth** [comment]
It's up here: http://multiformats.io/, you can get the hash via `ipfs resolve -r /ipns/multiformats.io`

The hash in the readme is likely from an older version.

**Comment by VictorBjelkholm** [comment]
Updated the hash in the readme to point to QmVhFMu7ryuFyRXm8gpxWmVuSsLR5H9Z91j8YcTrc9GmUL which is the current one.
