### ISSUE TITLE
enable google analytics

### ISSUE THREAD

**Issue by dharmapunk82** [multiformats/website#69]
code to add to site header: 

<script async src="https://www.googletagmanager.com/gtag/js?id=UA-96910779-10"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-96910779-10');
</script>

**Comment by Stebalien** [comment]
We usually use countly, but I'm not sure if anyone really cares about analytics for this site.

**Comment by Stebalien** [comment]
(please delete upstream tracking)
