### ISSUE TITLE
Deploy and setup CD

### ISSUE THREAD

**Issue by VictorBjelkholm** [multiformats/website#8]
We need to have a quick and efficient way of deploying multiformats.io when it changes.

**Comment by diasdavid** [comment]
we now have one thanks to the shiny makefile that is shared across all the websites! \o/

**Comment by VictorBjelkholm** [comment]
@diasdavid wait? How is the CD setup? Think you're confusing things here, this issue is referring to continuously deploying the website (on every commit, automatically deploy the website)
